[package]
name = "kawa-tool-box"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.29.0"
gtk = "0.18.2"
rig-core = { version = "0.17.1", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
